#MapBot Alpha Core Configuration
#Sun Jan 25 19:38:07 CST 2026
connection.reconnectInterval=5
connection.wsUrl=ws\://127.0.0.1\:7000
debug.debugMode=true
messaging.adminGroupId=885810515
messaging.adminQQs=
messaging.botQQ=2133782376
messaging.playerGroupId=875585697
redis.database=0
redis.enabled=true
redis.host=127.0.0.1
redis.password=
redis.port=6379
